#!/usr/bin/env python3
"""
Network Bridge Creator for ggNet

Creates a network bridge for diskless client communication.
Inspired by ggRock's network configuration.

Usage:
    python3 create_network_bridge.py <interface_name> <bridge_name>
    
Example:
    python3 create_network_bridge.py eth0 br0
"""

import sys
import subprocess
import os
import shutil
from datetime import datetime


def check_root():
    """Ensure script is run as root"""
    if os.geteuid() != 0:
        print("❌ This script must be run as root")
        print("   Usage: sudo python3 create_network_bridge.py <interface> <bridge>")
        sys.exit(1)


def backup_interfaces():
    """Backup /etc/network/interfaces"""
    interfaces_file = "/etc/network/interfaces"
    if os.path.exists(interfaces_file):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = f"{interfaces_file}.bak.{timestamp}"
        shutil.copy2(interfaces_file, backup_file)
        print(f"✅ Backed up {interfaces_file} to {backup_file}")
        return backup_file
    return None


def get_interface_config(interface):
    """Get current interface configuration"""
    try:
        # Check if interface exists
        result = subprocess.run(
            ['ip', 'link', 'show', interface],
            capture_output=True,
            text=True,
            check=True
        )
        
        # Get current IP address
        ip_result = subprocess.run(
            ['ip', '-4', 'addr', 'show', interface],
            capture_output=True,
            text=True
        )
        
        return {
            'exists': True,
            'output': result.stdout,
            'ip_info': ip_result.stdout
        }
    except subprocess.CalledProcessError:
        return {'exists': False}


def create_bridge_with_netplan(interface, bridge):
    """Create bridge using Netplan (Ubuntu 18.04+)"""
    netplan_file = "/etc/netplan/01-ggnet-bridge.yaml"
    
    config = f"""# ggNet Bridge Configuration
# Generated by ggNet installer
network:
  version: 2
  renderer: networkd
  ethernets:
    {interface}:
      dhcp4: false
      dhcp6: false
  bridges:
    {bridge}:
      interfaces: [{interface}]
      dhcp4: true
      parameters:
        stp: false
        forward-delay: 0
"""
    
    with open(netplan_file, 'w') as f:
        f.write(config)
    
    print(f"✅ Created Netplan config: {netplan_file}")
    print("📡 Applying network configuration...")
    
    try:
        subprocess.run(['netplan', 'apply'], check=True)
        print("✅ Bridge created successfully with Netplan")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to apply Netplan config: {e}")
        return False


def create_bridge_with_interfaces(interface, bridge):
    """Create bridge using /etc/network/interfaces (Debian)"""
    
    try:
        import debinterface
    except ImportError:
        print("⚠️  debinterface not installed, trying manual configuration...")
        return create_bridge_manual(interface, bridge)
    
    interfaces = debinterface.Interfaces()
    
    # Check if bridge already exists
    bridge_adapter = interfaces.getAdapter(bridge)
    
    if bridge_adapter is None:
        print(f"✅ {bridge} not found in interfaces, creating...")
        nic_adapter = interfaces.getAdapter(interface)
        
        if nic_adapter is None:
            print(f"✅ {interface} not found, creating with DHCP...")
            nic_adapter = interfaces.addAdapter({
                'name': interface,
                'addrFam': 'inet',
                'source': 'dhcp'
            })
        
        # Copy config from physical adapter
        bridge_adapter = nic_adapter
    else:
        print(f"ℹ️  {bridge} already exists, updating...")
    
    # Configure bridge
    bridge_adapter.setName(bridge)
    bridge_adapter.setAuto(True)
    bridge_adapter.setHotplug(False)
    
    bridge_options = {
        'ports': interface,
        'stp': 'off',
        'fd': '0'
    }
    bridge_adapter.setBropts(bridge_options)
    
    # Remove old physical adapter
    interfaces.removeAdapterByName(interface)
    
    # Create new physical adapter in manual mode
    physical_adapter_options = {
        'addrFam': 'inet',
        'name': interface,
        'source': 'manual'
    }
    interfaces.addAdapter(physical_adapter_options)
    
    # Write configuration
    interfaces.writeInterfaces()
    print("✅ Bridge created successfully with debinterface")
    
    return True


def create_bridge_manual(interface, bridge):
    """Manually create bridge configuration"""
    interfaces_file = "/etc/network/interfaces"
    
    # Get current IP config
    ip_info = subprocess.run(
        ['ip', '-4', 'addr', 'show', interface],
        capture_output=True,
        text=True
    )
    
    # Simple bridge configuration
    bridge_config = f"""
# ggNet Bridge Configuration
# Added by ggNet installer

# Physical interface (no IP)
auto {interface}
iface {interface} inet manual

# Bridge interface (gets IP)
auto {bridge}
iface {bridge} inet dhcp
    bridge_ports {interface}
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0
"""
    
    # Append to interfaces file
    with open(interfaces_file, 'a') as f:
        f.write(bridge_config)
    
    print("✅ Bridge configuration added to /etc/network/interfaces")
    print("⚠️  You'll need to restart networking: systemctl restart networking")
    
    return True


def enable_ip_forwarding():
    """Enable IP forwarding for iSCSI routing"""
    sysctl_conf = "/etc/sysctl.d/99-ggnet.conf"
    
    config = """# ggNet Network Configuration
# IP forwarding for iSCSI routing
net.ipv4.ip_forward = 1
"""
    
    with open(sysctl_conf, 'w') as f:
        f.write(config)
    
    # Apply immediately
    subprocess.run(['sysctl', '-p', sysctl_conf], check=True)
    print("✅ IP forwarding enabled")


def main():
    if len(sys.argv) != 3:
        print("""
ggNet Network Bridge Creator
============================

Creates a network bridge for diskless client communication.

Usage:
    sudo python3 create_network_bridge.py <interface_name> <bridge_name>

Example:
    sudo python3 create_network_bridge.py eth0 br0
    sudo python3 create_network_bridge.py enp2s0 vmbr0

Note:
    - The physical interface will be set to 'manual' mode
    - The bridge will be configured with DHCP
    - Original configuration will be backed up
    - Network service will be restarted
""")
        sys.exit(1)
    
    interface = sys.argv[1]
    bridge = sys.argv[2]
    
    print("=" * 60)
    print("  ggNet Network Bridge Creator")
    print("=" * 60)
    print()
    
    # Check root
    check_root()
    
    # Get interface info
    print(f"📡 Checking interface {interface}...")
    info = get_interface_config(interface)
    
    if not info['exists']:
        print(f"❌ Interface {interface} not found!")
        print("Available interfaces:")
        subprocess.run(['ip', 'link', 'show'])
        sys.exit(1)
    
    print(f"✅ Interface {interface} found")
    
    # Backup interfaces file
    print("\n💾 Backing up network configuration...")
    backup_file = backup_interfaces()
    
    # Detect which method to use
    print("\n🔧 Detecting network configuration method...")
    
    if os.path.exists('/etc/netplan'):
        print("✅ Detected Netplan (Ubuntu 18.04+)")
        success = create_bridge_with_netplan(interface, bridge)
    elif os.path.exists('/etc/network/interfaces'):
        print("✅ Detected /etc/network/interfaces (Debian)")
        success = create_bridge_with_interfaces(interface, bridge)
    else:
        print("⚠️  Unknown network configuration method, using manual...")
        success = create_bridge_manual(interface, bridge)
    
    if success:
        # Enable IP forwarding
        print("\n🌐 Enabling IP forwarding...")
        try:
            enable_ip_forwarding()
        except Exception as e:
            print(f"⚠️  Failed to enable IP forwarding: {e}")
        
        print("\n" + "=" * 60)
        print("  ✅ Bridge Creation Complete!")
        print("=" * 60)
        print()
        print(f"Bridge Name:     {bridge}")
        print(f"Physical Port:   {interface}")
        print(f"IP Forwarding:   Enabled")
        print(f"Backup File:     {backup_file}")
        print()
        print("⚠️  IMPORTANT:")
        print("   - Network service may restart automatically")
        print("   - You may temporarily lose connection")
        print("   - Verify connectivity after restart")
        print()
    else:
        print("\n❌ Bridge creation failed!")
        if backup_file:
            print(f"   You can restore from: {backup_file}")
        sys.exit(1)


if __name__ == "__main__":
    main()

